name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        bash setup.sh

    - name: Analysing the code with ruff
      id: ruff
      run: |
        tmp_dir=$(mktemp -d) &&
        git ls-files '*.py' | grep -v "PySide_src" | xargs -I {} cp --parents {} $tmp_dir &&
        poetry run ruff format $(find $tmp_dir -name '*.py') &&
        git ls-files '*.py' | grep -v "PySide_src" | while read -r file; do
          diff -u "$file" "$tmp_dir/$file"
        done &&
        rm -rf $tmp_dir
      continue-on-error: true